stages:
  - build
  - publish
  - test

image: docker:latest

variables:
  DOCKER_DRIVER: overlay2
  NAMESPACE: rjvandoesburg/gitlab-ci-pipeline-php

services:
  - docker:dind

before_script:
  - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD"

Debian 8.0:
  stage: build
  variables:
    IMAGE_VERSION: "8.0"
  script:
    - docker pull php:$IMAGE_VERSION || true
    - docker pull $NAMESPACE:$IMAGE_VERSION || true
    - docker build --compress --cache-from $NAMESPACE:$IMAGE_VERSION --build-arg VCS_REF=$CI_COMMIT_SHORT_SHA --build-arg BUILD_DATE=$(date -u +'%Y-%m-%dT%H:%M:%SZ') -t $NAMESPACE:$IMAGE_VERSION -f php/$IMAGE_VERSION/Dockerfile .
    - docker run -t --rm rjvandoesburg/gitlab-ci-pipeline-php:$IMAGE_VERSION -v
    - docker run -t --rm rjvandoesburg/gitlab-ci-pipeline-php:$IMAGE_VERSION -m
    - docker run -t --rm -v $(pwd):/var/www/html rjvandoesburg/gitlab-ci-pipeline-php:$IMAGE_VERSION goss -g tests/goss-$IMAGE_VERSION.yaml v
    - docker tag $NAMESPACE:$IMAGE_VERSION $NAMESPACE:latest
    - docker tag $NAMESPACE:$IMAGE_VERSION $NAMESPACE:8
    - docker push $NAMESPACE:$IMAGE_VERSION
    - docker push $NAMESPACE:8
    - docker push $NAMESPACE:latest
  when: always

FPM 8.0:
  stage: build
  variables:
    IMAGE_VERSION: "8.0-fpm"
  script:
    - docker pull php:$IMAGE_VERSION || true
    - docker pull $NAMESPACE:$IMAGE_VERSION || true
    - docker build --compress --cache-from $NAMESPACE:$IMAGE_VERSION --build-arg VCS_REF=$CI_COMMIT_SHORT_SHA --build-arg BUILD_DATE=$(date -u +'%Y-%m-%dT%H:%M:%SZ') -t $NAMESPACE:$IMAGE_VERSION -f php/8.0/fpm/Dockerfile .
    - docker run -t --rm -v $(pwd):/var/www/html $NAMESPACE:$IMAGE_VERSION goss -g tests/goss-8.0.yaml v
    - docker tag $NAMESPACE:$IMAGE_VERSION $NAMESPACE:fpm
    - docker push $NAMESPACE:$IMAGE_VERSION
    - docker push $NAMESPACE:fpm
  when: always
